### PR TITLE
Update included HDF5-Blosc to v1.0.1 (build&doc, minor&format fixes)

### PR DESCRIPTION
**Pull request by ivilata**
The only remaining difference is how the Fletcher32 filter is applied last in the example source.

### CODE REVIEW

**Comment by ivilata** [comment]
BTW, I created Blosc/hdf5-blosc#36 to also apply the example code change in the original source.

**Review by avalentino — APPROVED** [review]

**Review by FrancescAlted — APPROVED** [review]
That's great!  Thanks for the effort in doing this.

**Comment by ivilata** [comment]
Since Blosc/hdf5-blosc#36 was merged, both code bases are identical again. It may be worth considering using a submodule for `c-blosc` instead of a source copy.

**Comment by avalentino** [comment]
yes, I agree

**Pull request merged**
