### PR TITLE
Add linux aarch64 wheel support

### PR DESCRIPTION
**Pull request by odidev**
Added linux aarch64 wheel support.
Related to #891. @avalentino Could you please review this PR.

### CODE REVIEW

**Comment by avalentino** [comment]
Dear @odidev the PR look good to me and we are interesting in providing support for different architectures.
Anyway there are other ongoing activities related to wheel enhancements e.g. #872.
Before going on with the merge I would like to have some feedback/coordination form e.g. @amotl to be sure the this is in line with plans that he has.
Feedback form other developers is of course welcome.

**Comment by avalentino** [comment]
OK, no feedback.
Merging ...
Thanks @odidev

**Comment by odidev** [comment]
@avalentino, could you please let me know the plans for releasing AArch64 wheels? Thanks in advance.

**Comment by avalentino** [comment]
At the moment we are not able to release because windows wheels do not work

**Pull request merged**
