### PR TITLE
Drop Python 3.5 support, use f-strings and underscores in integers 

### LINKED ISSUE #840: Dropping Python 3.5 support
Python 3.5 is after end-of-life since 2020-09-30. Dropping its support would allow introduction of f-strings and keep the development modern. In #839 the codebase has already been `pyupgrade`d to Python 3 and some old Python 2 import hacks have been removed.

To abandon Python 3.5 properly, one of the next versions of PyTables should announce the deprecation of Python 3.5.

### PR DESCRIPTION
**Pull request by eumiro**
This drops Python 3.5 support from CIs and PyPI metadata. PyTables will be then Python 3.6+ and this introduces following new syntax features: 

- PEP 498, formatted string literals.
- PEP 515, underscores in numeric literals.
- PEP 526, syntax for variable annotations.
- PEP 525, asynchronous generators.
- PEP 530: asynchronous comprehensions.

The first two can be added automatically using `pyupgrade` and manually. Variable annotations should be discussed. Async stuff is not relevant for PyTables yet.

Closes #840

### CODE REVIEW

**Review by avalentino — APPROVED** [review]
LGTM.
Thanks @eumiro

**Comment by avalentino** [comment]
Ups, I haven't realized this is still in draft, sorry

**Comment by eumiro** [comment]
Sorry, @avalentino these were the two first steps. The third one (manually converting the rest of the string formatting to f-strings) is under way, but of course takes a little bit more time (and the review will probably too be more work). But I will already merge this and do the rest in a new PR.

**Comment by eumiro** [comment]
@avalentino the https://github.com/PyTables/PyTables/runs/1629625410 failed because it wanted to `Building cp35-manylinux_x86_64 wheel` and we are now beyond 3.5 with the f-strings.

In the file https://github.com/PyTables/PyTables/blob/master/.github/workflows/wheels.yml there's no mention of 3.5, but there is the line 40: `CIBW_SKIP: "cp27-* pp*"`. Is it possible, that `cp35` is on some list and we have to skip it here?

**Comment by avalentino** [comment]
> In the file https://github.com/PyTables/PyTables/blob/master/.github/workflows/wheels.yml there's no mention of 3.5, but there is the line 40: CIBW_SKIP: "cp27-* pp*". Is it possible, that cp35 is on some list and we have to skip it here?

@eumiro  yes, correct.
Adding "cp55-*" to CIBW_SKIP should be enough.

Sorry the workflow for building wheels is only on master and releases because it takes very long time to run

**Comment by eumiro** [comment]
Oh yes, the list is here: https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip

I replaced `CIBW_SKIP` with `CIBW_BUILD` to have an explicit list of versions to support. A future us will have easier time to add/drop Python versions.

**Pull request merged**
