### PR TITLE
Release 3.2.3

### PR DESCRIPTION
**Pull request by tomkooij**
This an attempt to prepare release 3.2.3

I cherry-picked all bugfixes from `develop` and anything that seemed minor enough not to break things. I have pasted the release notes below. The current PR passes the `--heavy` tests.

I skipped large PRs such as #493, #519, #541 and #543. 

ToDo:
 - [x] ~~Make a PR of #553 to `master` and~~ make sure it gets in this release.
 - [x] cherry-pick #559 c-blosc 1.9.2
 - [x] try to get #561 in.
 - [x] handle #539  (`test_indexvalues.py` fails on python 3.5)
 - [x] ~~handle #545 (HDF5 1.10 break pytables)~~ up to package maintainers.
 - [x] Double check the release notes
 - [x] Run `--heavy` tests (after #553 is merged)
 - [x] set `VERSION` to 3.2.3 

```
Improvements
------------

- It is now possible to use HDF5 with the new shared library naming scheme
  (>= 1.8.10, hdf5.dll instead of hdf5dll.dll) on Windows (:issue:`540`).
  Thanks to Tadeu Manoel.
- Now :program: `ptdump` sorts output by node name and does not print a
  backtrace if file cannot be opened.
  Thanks to Zbigniew Jędrzejewski-Szmek.


Bugs fixed
----------

- Only run `tables.tests.test_basics.UnicodeFilename` if the filesystem
  encoding is utf-8. Closes :issue:`485`.
- Add lib64 to posix search path. (closes :issue:`507`)
  Thanks to Mehdi Sadeghi.
- Ensure cache entries are removed if fewer than 10 (closes :issue:`529`).
  Thanks to Graham Jones.
- Fix segmentation fault in a number of test cases that use
  :class:`index.Index` (closes :issue:`532` and :issue:`533`).
  Thanks to Diane Trout.
- Fixed the evaluation of transcendental functions when numexpr is
  compiled with VML support (closes :issue:`534`, PR #536).
  Thanks to Tom Kooij.
- Make sure that index classes use buffersizes that are a multiple
  of chunkshape[0] (closes :issue:`538`, PR #538).
  Thanks to Tom Kooij.
- Ensure benchmark paths exist before benchmarks are executed (PR #544).
  Thanks to rohitjamuar.
```

### CODE REVIEW

**Comment by andreabedini** [comment]
Wow @tomkooij, that's some great work right there. I will make sure I'll run some tests too.

**Comment by FrancescAlted** [comment]
Great work @tomkooij .  Perhaps you already saw it, but just in case:
https://github.com/PyTables/PyTables/wiki/Release-Procedure

I'll try to update the c-blosc sources later today so that they can be included in the release.

**Comment by andreabedini** [comment]
@tomkooij please be aware of #488 while making the source release.

**Comment by tomkooij** [comment]
I ran the `--heavy` tests on `master` with this PR merged python 3 overnight. I'm getting many errors from `test_indexvalues` (348 identical failures).

I'll rerun the tests on the current `master` overnight, to see if it is a commit from this PR.


```
======================================================================
FAIL: None (tables.tests.test_indexvalues.UIHSV13aTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/python3/Pytables/build/lib.linux-x86_64-3.5/tables/tests/test_indexvalues.py", line 136, in test0
1a
    table1.where('(il<=t1var1)&(t1var1<=sl)')]
  File "/python3/Pytables/build/lib.linux-x86_64-3.5/tables/table.py", line 1544, in where
    return self._where(condition, condvars, start, stop, step)
  File "/python3/Pytables/build/lib.linux-x86_64-3.5/tables/table.py", line 1583, in _where
    return row._iter(start, stop, step, chunkmap=chunkmap)
  File "tables/tableextension.pyx", line 797, in tables.tableextension.Row._iter (tables/tableextension.c:9591)
  File "tables/tableextension.pyx", line 879, in tables.tableextension.Row._init_loop (tables/tableextension.c:10654)
AssertionError
```

**Comment by tomkooij** [comment]
This should be all. Running `--heavy` tests on 2.7 and 3.5 overnight.

I'm having some second thoughts about handling the HDF 1.10 incompatibilty. @FrancescAlted @andreabedini : I will update the prerequisites in `doc/source/userguide/installation.rst` before release.
Do we need to also explicitly handle this in `setup.py`?

**Comment by FrancescAlted** [comment]
Could you share which are those second thoughts?

**Comment by tomkooij** [comment]
I had second thoughts about not doing anything in `setup.py` to prevent using HDF5 1.10.x. I added a check (79bebcb) that just fails when detecting HDF5 >= 1.10. IMO, that should be enough.
.
I updated (cherry-picked) the installation instructions in the userguide and added a comment about HDF5 v1.10.

**Comment by FrancescAlted** [comment]
I see. :+1:

**Comment by tomkooij** [comment]
This is it! 

I set the release date to tommorow. I'll merge this and do the rest of the release stuff tomorrow. (Not enough time today to do it properly).

**Comment by FrancescAlted** [comment]
Looks good to me. Just don't forget to update the RELEASE_NOTES.txt before the release.

**Comment by avalentino** [comment]
Thank you very much @tomkooij 
All tests pass here, both with Python 2 and Python 3.

**Pull request merged**
