### PR TITLE
Update to use HDF5 1.8.16 (naming and minor API changes)

### PR DESCRIPTION
**Pull request by tadeu**
I'm updating it to work with the CMake built HDF5 1.8.16 in Windows.
I've also picked a commit from c-blosc that fixes it for HDF5 1.8.16.

### CODE REVIEW

**Comment by avalentino** [comment]
Thank you @tadeu.
My only concern is that i would like to keep the compatibility with old HDF5 layout.
Ideas?

**Comment by FrancescAlted** [comment]
The PR by @tadeu is just backporting something in blosc-hdf5 repository, so it should be really safe to merge it, unless you @avalentino has some specific concerns.

**Comment by avalentino** [comment]
@FrancescAlted I was just worried about the library filename change hdf5dll.dll --> hdf5.dll
Honestly I didn't checked which is the last "official" binary distribution that uses the old naming.

**Comment by FrancescAlted** [comment]
Good point @avalentino.  @tadeu, please could you make some experiments with earlier HDF5 versions and tell us which versions your modification will compatible with?  If you can provide some kind of backward compatibility with older version, that would be really great.  Thanks!

**Comment by avalentino** [comment]
The old naming schema has been used up to HDF5 1.8.10 (November 2014) in "official" binary packages.
For PyTables the minimum supported version is HDF5 >= 1.8.4 (>=1.8.7 is strongly recommended).

If the patch for keeping backward compatibility is too complex we could just drop support for HDF5 < 1.8.11 (May 2013) on Windows.

It should not be a big issue IMO.

**Comment by tadeu** [comment]
Well noted @avalentino, I'll try to make it backwards compatible.

**Comment by tadeu** [comment]
I've modified the commit to add backward compatibility and tested it with both HDF 1.8.8 and 1.8.16

**Comment by FrancescAlted** [comment]
Looks good to me.  @tadeu could you please update the RELEASE_NOTES accordingly please?  After that I will merge.  Thanks!

**Comment by tadeu** [comment]
Done

**Pull request merged**
