### PR TITLE
Remove old api

### PR DESCRIPTION
**Pull request by andreabedini**
This is a first stab at #320, it removes _past.py and all occurrences of previous_api and previous_api_property. What's left?

Not sure about `tables/scripts/pt2to3.py`, I included in it `old2newnames` and `new2oldnames` from `_past.py`. I hope it still works.

### CODE REVIEW

**Comment by andreabedini** [comment]
@avalentino go to https://github.com/settings/applications to check what's using your github credentials to automatically put the label *in progress*

**Comment by avalentino** [comment]
> @avalentino go to https://github.com/settings/applications to check what's using your github credentials to automatically put the label in progress

OK I hope I have addressed the problem by disabling waffle.io.
Please let me know if you keep seeing strange like this one in the future.

Please feel free to change the label to reflect the current status of the work.

I assigned this Milestone 3.3.
If it is OK for you I would like to keep this on a separate branch (do not merge into develop) until we are sure that there will be no new release in the 3.2.x line.

Regarding the #320 IMO most of the job is addressed by this PR.

Maybe we should review of the docs to
* remove remaining references to the old API (probably it is already OK)
* document the final step of the transition to the new API more in detail.

**Comment by andreabedini** [comment]
Happy to keep it on a separate branch, but 3.2.x releases would come out of the release-3.2 branch right? not from develop, which is where we merge new stuff (according to http://nvie.com/posts/a-successful-git-branching-model/)

**Comment by andreabedini** [comment]
can I merge into develop?

**Comment by avalentino** [comment]
> Happy to keep it on a separate branch, but 3.2.x releases would come out of the release-3.2 branch right?

Actually it is not. Release branches are generated from develop and deleted after the release.
IMO there is till the possibility that we need a bug fix release in relatively short time so I would prefer to wait before merging the remove-old api branch.

**Comment by andreabedini** [comment]
@avalentino I thought we were following this http://nvie.com/posts/a-successful-git-branching-model/ ? the develop branch should be for "next version" not for bug fix releases (which come out the release branch). We need to be able to commit both bug fixes for say 3.2.1 (see #455) and big stuff for next release (like this PR and other things I am working on). I have also been committing to develop things that, although lightweight, are not really meant for 3.2.1.

**Comment by avalentino** [comment]
We do not support more than one development line at time. Once we release 3.3.0 there will never be a 3.2.1.
Anything that do not change the API, behaviours and does not introduces new functions can go in 3.2.1 IMO.
If we merge this PR the the next release have to be 3.3.0 even if there are no relevant feature changes.

**Comment by andreabedini** [comment]
> If we merge this PR the the next release have to be 3.3.0 even if there are no relevant feature changes.

Can we do this then?

**Comment by avalentino** [comment]
>> If we merge this PR the the next release have to be 3.3.0 even if there are no relevant feature changes.

> Can we do this then?

IMO we should wait some more, as I said.

**Comment by andreabedini** [comment]
Sorry @avalentino but I am a bit frustrated here. I am trying to put some energy to revitalise this project but I am asked to sit down and wait for Godot.

What prevents you from doing a 3.2.1 release out of master if necessary (and it is likely going to be, given the indexes extension problem)?

Alternatively, if you really what to do releases out of develop rather than master, would you be ok if I create a developdevelop branch? and do the long term work there?

**Comment by andreabedini** [comment]
I am merging this into develop branch, open a new issue if anything comes up.

**Pull request merged**
