### PR TITLE
Fix windows packaging for python 3.8 (again)

### PR DESCRIPTION
**Pull request by tomkooij**
Python 3.8 changes DLL resolution. Unfortunately v3.6.x does not fix all issues... Packaging sucks.

The current `setup.py` and `__init__.py` break conda packages for python >= 3.8 (verified) and probably wheels as well: Appveyor tests on windows fail on py3.7 but not on py3.6. (Backported py38 feature in 3.7.6??)

Try to fix by:
 - remove preloading of DLLs using `ctypes.cdll.LoadLibrary` (`__init__.py`)
 - ~add DLLs to `package_data` instead of `data_files` in `setup.py`~

TODO:
 - [x] investigate and fix the appveyor failure
 - [x] test conda package (py37) 
 - [x] test conda package (py38) 
 - [x] test wheel (py37) 
 - [x] test wheel (py38) 
I will probably need to do these tests on my local Windows machine. Will take some time.

### CODE REVIEW

**Comment by tomkooij** [comment]
512b935 is consistent with master: 
 - python3.6/appveyor/windows passes. 
 - python3.7/appveyor/windows fails with a DLL import failure when testing the build wheel.

**Comment by tomkooij** [comment]
The appveyor CI failure was due to missing `zlib.dll` AGAIN. (This is by far the most common hdf5.dll import problem: hdf5.dll depends on zlib.dll)

**Comment by tomkooij** [comment]
This seems ok. I'll check the conda-forge packages (CI currently building) and merge if they work as expected.

**Comment by dragoljub** [comment]
@tomkooij Any luck getting LZO compression to show up with pytables and Python 3.8 in Windows? I'm trying to include the lzo2.dll and hoped it would show up when I imported tables like it does on Python 3.7.

From my Python 3.7 install LZO shows up but on the new Python 3.8 imports I can't get LZO to show up.
```
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tables

In [2]: tables.print_versions()
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.6.1
HDF5 version:        1.10.4
NumPy version:       1.17.1
Numexpr version:     2.7.0 (using VML/MKL 2019.0.4)
Zlib version:        1.2.11 (in Python interpreter)
LZO version:         2.10 (Mar 01 2017)
Blosc version:       1.16.3 (2019-03-08)
Blosc compressors:   blosclz (1.1.0), lz4 (1.8.3), lz4hc (1.8.3), snappy (1.1.1), zlib (1.2.11), zstd (1.3.8)
Blosc filters:       shuffle, bitshuffle
Cython version:      0.29.13
Python version:      3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)]
Platform:            Windows-10-10.0.17763-SP0
Byte-ordering:       little
Detected cores:      8
Default encoding:    utf-8
Default FS encoding: utf-8
Default locale:      (en_US, cp1252)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
```

**Pull request merged**
