### PR TITLE
Patch to find runtime dir on macOS

### PR DESCRIPTION
**Pull request by outpaddling**
This fixes failures  of ctypes.CDLL() to find locate dylibs on macOS, per #1219.

### CODE REVIEW

**Comment by avalentino** [comment]
@outpaddling thanks fo resubmitting the PR.
Apparently there is something that breaks many CI tasks, even if, apparently, the changes look quite innocuous.
Do you have an idea of what is happening?

**Comment by outpaddling** [comment]
Does the CI system scan for the word "Error" in the build output?  That's the only thing I can think of.  I added

```
else
    print("Error: path is not set.")
```
It builds fine for me under pkgsrc on Alma, macOS, and NetBSD.

**Comment by avalentino** [comment]
Hi @outpaddling 
tests were failing due to an unrelated issue that should now be fixed in the master branch.
Could I kindly ask you to rebase you changes into master and (force) push?

The PT looks mostly fine, even if I would prefer to not `print` too many debug messages.

**Comment by avalentino** [comment]
@outpaddling unfortunately there seem to be some issues connected to the change that you are proposing.
Any idea about how to proceed?

**Review by avalentino — APPROVED** [review]

**Comment by avalentino** [comment]
Thanks @outpaddling

**Comment by outpaddling** [comment]
I have no idea why the checks passed this time.  ;-)  All I did was remove a warning print() and eliminate a variable, using the expression directly instead.

**Pull request merged**
