### PR TITLE
Release 3.4.0

### PR DESCRIPTION
**Pull request by tomkooij**
There are a few bugfixes that have been in unreleased too long. And this will release HDF5 1.10 compatibility.

Version number should be 3.4.0 because of HDF5-1.10 compatibility.

TODO:
 - [x] merge latest Blosc
 - [x] merge #576 
 - [ ] Run `--heavy` tests
 - [x] Update changelog
 - [ ] Follow release procedure

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Nice bunch of improvements! Let me see if I can update Blosc to the latest version. Should I send a PR against this branch or development?

**Comment by tomkooij** [comment]
Ok! @FrancescAlted: Just PR against develop. I'll merge that in.

**Comment by tomkooij** [comment]
I intend to run the `--heavy` testsuite sunday night (GMT). I'll accept PRs for 3.4.0 until then (but I do not really anticipate anything new)

**Comment by andreabedini** [comment]
@tomkooij #576 works now! am I in time?

**Comment by tomkooij** [comment]
@andreabedini : Ehhhhh....

Not in time. But I'll include it anyway, since we are (I am) not going to release again soon (I hope emergency bugfixes won't be necessary this time).

I having `make dist` fail on me anyway, so there is still some work to do.

**Comment by andreabedini** [comment]
> @andreabedini : Ehhhhh....
> 
> Not in time. But I'll include it anyway, since we are (I am) not going to release again soon (I hope emergency bugfixes won't be necessary this time).

<3

> I having make dist fail on me anyway, so there is still some work to do.

What's happening with that one? can I help?

**Comment by tomkooij** [comment]
@andreabedini : Thanks! It turns out to be something I came across before (but did not document):

I have to change `VERSION` first. Then `python setup.py install` that version. Then `make dist` or the docs/sphinx will fail.

I'll update the release procedure in the Wiki.

**Comment by tomkooij** [comment]
All set now. If this passes I will do a final run of the heavy testsuite and do the actual release.

**Comment by tomkooij** [comment]
Still to do:
 - The Mac OSX wheelbuilder failed on some configuration thing. No OSX wheels yet.
 - building the PDF docs failed. Probably my local LaTeX config.
 - I have to figure out how readthedocs works.
 - Post ANN messages
 - Notify Numfocus for april newsletter

**Pull request merged**
