### PR TITLE
Update documentation build-chain

### LINKED ISSUE #574: Docs don't build on python 3
There is python 2 code in `doc/spinhxext`. This breaks `make dist` (and make in `/doc`) on python 3 because sphinx fails on the python 2 code. (No `lib2to3` conversion by setup.py, now that we have single codebase python 2/3)

We should at least make the code run on python 3 (and preferably single codebase 2/3). Running `2to3` is probably enough.

### PR DESCRIPTION
**Pull request by andreabedini**
Building documentation might or might not work with Python 2.
(StringIO being the culprit).

Closes #574.

### CODE REVIEW

**Comment by tomkooij** [comment]
With 11bd422 this seems to build the docs on python 2 as well. I have not tested python 3.

I couldn't find an alias in `six` to substitute the try / except in 11bd422. There is `futurize.builtins.str` but that would mean another dependency.

**Comment by andreabedini** [comment]
I don't know exactly when things changed but [our docs on readthedoc](http://pytables.readthedocs.io/en/latest/) started building just fine (they didn't use to). I always wanted to split the documents from the website (like h5py does).

**Comment by tomkooij** [comment]
@andreabedini: I didn't know we had docs on pytables.readthedocs.io. (They are both outdated and not correctly build, usersguide/libref is wrong). 

We also have docs on [pytables.org](pytables.org). I guess we should get rid off one, or link them. We have to different versions at the moment.

**Comment by andreabedini** [comment]
@tomkooij yeah, it's actually not entirely intentional :) see e.g. #460 #453

**Comment by andreabedini** [comment]
I'll go ahead and merge this.

**Comment by andreabedini** [comment]
@avalentino could you add me (and @tomkooij perhaps) as owners on the pytables project on readthedocs? cheers

**Comment by avalentino** [comment]
> @avalentino could you add me (and @tomkooij perhaps) as owners on the pytables project on readthedocs? cheers

sure, @andreabedini has been added but @tomkooij seems to not exist.
Tom, which is you rtd user ID?

**Comment by andreabedini** [comment]
@avalentino Thanks! oh @tomkooij might not have an account on RTD ...

**Comment by tomkooij** [comment]
@avalentino : Just created `tomkooij` on readthedocs.io

**Comment by avalentino** [comment]
> @avalentino Thanks! oh @tomkooij might not have an account on RTD ...

done
tthanks

**Comment by andreabedini** [comment]
Thanks @avalentino. I couldn't get RTD to work yet, https://readthedocs.org/projects/pytables/builds/4758193/

**Comment by andreabedini** [comment]
@PyTables/maintainers btw http://pytables.readthedocs.io/en/stable/ now works ok

**Comment by avalentino** [comment]
Thank you @andreabedini

**Comment by tomkooij** [comment]
Yes! Thanks!

**Comment by FrancescAlted** [comment]
Great work @andreabedini !

**Comment by andreabedini** [comment]
@avalentino @FrancescAlted @tomkooij hold your excitement, last build failed https://readthedocs.org/projects/pytables/builds/5282078/ :) but we are close!

**Comment by tomkooij** [comment]
if we `export HDF5_DIR=$CONDA_PREFIX` it will probably work. But I can't find howto set an environment variable in the readthedocs build system.
I don't think env variables in conda envs will end up in `enviroment.yml` so that's no use either.

I suggest a more general addition to `setup.py`: Set `HDF5_DIR` to `$CONDA_PREFIX` if the former is undefined and the latter is. (i.e. detect and use conda env)

**Comment by FrancescAlted** [comment]
Your suggestion for setting `HDF5_DIR` to `$CONDA_PREFIX` seems very nice to me, so +1

**Comment by tomkooij** [comment]
Well, #615 did not fix this. I'm guessing RTD creates a conda env but does not activate it when `python setup.py install --force` runs. The build shows `PKGCONFIG: True` which means `CONDA_PREFIX` was not detected by setup.py.

**Pull request merged**
