### PR TITLE
Use integer division

### PR DESCRIPTION
**Pull request by sethtroisi**
`cython -3` complaining about not being able to cast double to int in these locations.

```
Error compiling Cython file:
------------------------------------------------------------
...

--
  while lo < hi:
    mid = (lo+hi)/2
                ^
------------------------------------------------------------

tables/utilsextension.pyx:253:17: Cannot assign type 'double' to 'int'
```

### CODE REVIEW

**Review by avalentino — APPROVED** [review]
LGTM

**Comment by avalentino** [comment]
Thanks @sethtroisi , nice enhancement.
With this change are you able to build PyTables with cython language level 3/3str?

**Comment by sethtroisi** [comment]
Google's build system is successfully building this with `cython -3`; We pass these COPTs I didn't change the list so some of these may not be required. Build on my personal computer I'm getting errors about gil and hdf5_blosc but that be just my incomplete local setup.

[
    "-DNDEBUG",
    "-Isrc",
    "-Ithird_party/blosc",
    "-Ithird_party/py/tables/hdf5_blosc/src",
    "-Wno-incompatible-pointer-types-discards-qualifiers",
    "-Wno-self-assign",
    "-Wno-unused-variable",
    "-Wno-incompatible-pointer-types",
]

**Comment by avalentino** [comment]
@sethtroisi thanks for the extremely interesting feedback.
I would have expected more problems related to str/bytes usage.

**Pull request merged**
