### PR TITLE
PyTables v3.10.0 release

### PR DESCRIPTION
**Pull request by ivilata**
See the thread "Preparing for PyTables v3.10" in the `pytables-dev` mailing list.

### CODE REVIEW

**Comment by ivilata** [comment]
@avalentino, I didn't assign the PR so that you can choose whether to do the release yourself or leave it to me, as you prefer. Thanks! :slightly_smiling_face:

**Comment by ivilata** [comment]
(I'll give a shot to writing the release notes blurb and announcement in the meanwhile.)

**Review by avalentino — APPROVED** [review]
LGTM

**Comment by avalentino** [comment]
Thanks @ivilata please go ahead with the new release.

**Comment by ivilata** [comment]
Thanks @avalentino, I assigned the PR to myself.

**Pull request merged**
