### PR TITLE
Docs: cookbook: update inherit from Table

### PR DESCRIPTION
**Pull request by tomkooij**
Thanks to @molpopgen gh-649

### CODE REVIEW

**Comment by molpopgen** [comment]
The PR has a bit of a problem.  It contains text describing the issue at the end (see last paragraph).  While the PR fixes one issue (the old example didn't work easily), it does not address the bigger issue, which is that it seems wrong to inherit from Table.

**Comment by tomkooij** [comment]
I reopened the issue. The solution seems to be to documented as "do not do this", with the example showing why.

**Comment by molpopgen** [comment]
Ok.  Is there a recommended way to support custom types?  There are allusions to inheriting from "isDescription" in the Table docs--is that related?  If so, is there an example?

**Comment by tomkooij** [comment]
I'm moving this from this (closed) PR to the original issue, so we can track this #649

**Pull request merged**
