### PR TITLE
Release 3.3

### PR DESCRIPTION
**Pull request by tomkooij**
This is `master` with `develop` merged into it.

Intended for release as 3.3.

ToDo (before merge) (https://github.com/PyTables/PyTables/wiki/Release-Procedure) 
- [x] **Remove python 2.6 and python 3.3 support**. Remove from CI.
- [x] Have a closer look at some warnings in tests. (Deprecation warnings from numpy)
- [x] Run `--heavy` tests on Linux and Windows.
- [x] Update RELEASE-NOTES.txt
- [x] Update VERSION

### CODE REVIEW

**Comment by andreabedini** [comment]
epic! @tomkooij if you are unsure about anything, don't hesitate to give a shout

**Comment by tomkooij** [comment]
I'm running the `--heavy` tests overnight. I ran them last night, but I fixed some warnings. I'll rerun on Linux, and test on Windows as well. Probably overkill, but better safe than sorry.

I'm not sure if I'm missingsomething important in RELEASE_NOTES.txt (I added Blosc 1.11.1 and the Single codebase PR). If somebody spots something that needs a mention in the release notes: Let me know. (Many of the commits above have already been released as 3.2.3)

@PyTables/core: Please review. I intend to merge this (and continue with the release actions) as soon as the `--heavy` tests pass and this is reviewed.

**Comment by tomkooij** [comment]
This may not be the best place to ask, but... : Can we add @PyTables/core to @PyTablesBot on AppVeyor? https://www.appveyor.com/docs/team-setup/#github-integration 

I cannot cancel appveyor builds at this time, which would be nice.

**Comment by andreabedini** [comment]
> This may not be the best place to ask, but... : Can we add @PyTables/core to @PyTablesBot on AppVeyor? https://www.appveyor.com/docs/team-setup/#github-integration

In principle I have no problem with adding PyTablesBot to the core team, but 1) who is controlling PyTablesBot at the moment? what is that used for? 2) why do we need to do it? I skimmed through the page you linked but I didn't get it

**Comment by tomkooij** [comment]
@andreabedini: PyTablesBot is the admin account on AppVeyor linked to the PyTables team/organisation on GitHub. This user on AppVeyor (whoever controls it) should be able to add the PyTables/core team, so that we can cancel builds etc. 

Not high priority, just nice to have.

**Comment by tomkooij** [comment]
This looks finished. `--heavy` tests pass.

I intend to release this next week (monday if possible), so let me know if there is anything missing.

**Comment by FrancescAlted** [comment]
Hey, this looks really good.  +1 for releasing as soon as possible.  Thanks a bunch for this!

Regarding the PyTablesBot, I don't know anything about it.  Anyone?

**Comment by avalentino** [comment]
+1 for releasing, thanks @tomkooij 

Regarding PyTablesBot, not sure I have access to the PyTables project on appveyor.
Maybe @joshmoore can have some more info

**Comment by tomkooij** [comment]
Is there any reason we are tagging releases with `v.3.2.3` instead of  `v3.2.3` (without the dot after `v`) ? 

I'd rather tag the next release as `v3.3`

**Comment by FrancescAlted** [comment]
I don't think there is a reason for a 'v.' so +1 for the change.

Also, I suggest to use semver, so I'd go with 3.3.0 and 'v3.3.0' for the tag

Sent from my phone

El 11 set 2016, a les 10:58, Tom Kooij <notifications@github.com> va escriure:

**Comment by andreabedini** [comment]
@tomkooij agree with removing the dot, I wanted to do this for a while!

**Pull request merged**
