### PR TITLE
Release 3.4.3

### PR DESCRIPTION
**Pull request by jsancho-gpl**
release 3.4.3 : maintenance / bugfix release

TODO:
- [x] update `RELEASE-NOTES.txt` and `doc/source/release_notes.rst`
- [x] set `VERSION` to `3.4.3` (perhaps also in docs?)
- [x] run `--heavy` test suite on Linux (or Mac)
- [ ] run `--heavy` test suite on Windows.
- [ ] merge into `master`
- [x] make sure docs are also built / updated
- [x] upload packages to PyPI
- [ ] create wheels and upload to PyPI (wheel builder at `MacPython/pytables-wheels`)
- [ ] update `conda-forge/pytables-feedstock` 

After release:
- [ ] post release actions (3c5f652) (merge master back into `develop`)

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Also, I'd like to update blosc sources to latest release (1.14.3).  Should be easy enough.

**Comment by tomkooij** [comment]
About the conda error: We (also) test against HDF5 1.10.x, but that is not in conda `defaults` or `conda-forge`. This uses my version of hdf5-1.10 from my conda repos.

But that seems to be broken. I'll have a look.

**Comment by tomkooij** [comment]
@jsancho-gpl : I have created a TODO list above.  :-)

I can run the `--heavy` tests on Windows if you do not a have windows machine available.

(I can/should probably help with the wheels and conda-forge as well)

**Comment by jsancho-gpl** [comment]
Thanks @tomkooij, I don't have a Windows machine so I'll need your help for that. I'm working with the rest of the list.

**Comment by jsancho-gpl** [comment]
When running heavy test on Linux, I get:

```
/home/jsancho/.local/lib/python3.6/site-packages/tables-3.4.3-py3.6-linux-x86_64.egg/tables/nodes/filenode.py:170: UserWarning: host PyTables file is already closed!
  warnings.warn("host PyTables file is already closed!")
......
======================================================================
ERROR: None (tables.tests.test_tables.LargeRowSize)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jsancho/.local/lib/python3.6/site-packages/tables-3.4.3-py3.6-linux-x86_64.egg/tables/tests/test_tables.py", line 5126, in test01
    self.h5file.create_table(self.h5file.root, 'largerow', r)
  File "/home/jsancho/.local/lib/python3.6/site-packages/tables-3.4.3-py3.6-linux-x86_64.egg/tables/file.py", line 1066, in create_table
    track_times=track_times)
  File "/home/jsancho/.local/lib/python3.6/site-packages/tables-3.4.3-py3.6-linux-x86_64.egg/tables/table.py", line 842, in __init__
    byteorder, _log, track_times)
  File "/home/jsancho/.local/lib/python3.6/site-packages/tables-3.4.3-py3.6-linux-x86_64.egg/tables/leaf.py", line 290, in __init__
    super(Leaf, self).__init__(parentnode, name, _log)
  File "/home/jsancho/.local/lib/python3.6/site-packages/tables-3.4.3-py3.6-linux-x86_64.egg/tables/node.py", line 266, in __init__
    self._v_objectid = self._g_create()
  File "/home/jsancho/.local/lib/python3.6/site-packages/tables-3.4.3-py3.6-linux-x86_64.egg/tables/table.py", line 1029, in _g_create
    self._v_new_title, self.filters.complib or '', obversion)
  File "tables/tableextension.pyx", line 211, in tables.tableextension.Table._create_table
tables.exceptions.HDF5ExtError: Problems creating the table

----------------------------------------------------------------------
Ran 67132 tests in 9642.535s

FAILED (errors=1, skipped=304)
```

Any ideas?

**Comment by avalentino** [comment]
All seems to work fine here

```
$ python3 tables/tests/test_tables.py --heavy -v LargeRowSize
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.3.0
HDF5 version:        1.10.0-patch1
NumPy version:       1.12.1
Numexpr version:     2.6.2 (not using Intel's VML/MKL)
Zlib version:        1.2.11 (in Python interpreter)
LZO version:         2.08 (Jun 29 2014)
BZIP2 version:       1.0.6 (6-Sept-2010)
Blosc version:       1.11.1 (2016-09-03)
Blosc compressors:   blosclz (1.0.5), lz4 (1.7.1), lz4hc (1.7.1), snappy (unknown), zlib (1.2.11), zstd (1.2.0)
Blosc filters:       shuffle, bitshuffle
Cython version:      0.25.2
Python version:      3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0]
Platform:            Linux-4.13.0-38-generic-x86_64-with-Ubuntu-17.10-artful
Byte-ordering:       little
Detected cores:      4
Default encoding:    utf-8
Default FS encoding: utf-8
Default locale:      (it_IT, UTF-8)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
test00 (__main__.LargeRowSize)
Checking saving a Table with a moderately large rowsize ... ok
test01 (__main__.LargeRowSize)
Checking saving a Table with an extremely large rowsize ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.014s

OK
```

**Comment by tomkooij** [comment]
I can't reproduce: I think just ignoring the error is fine. (Or perhaps run that specific test again?)

**Comment by jsancho-gpl** [comment]
I've tried with Debian and Ubuntu in two different computers but always with the same result, error with LargeRowSize test. Probably I've something wrong in my tests environment. Maybe some kernel parameter for files size or something like that?

**Comment by jsancho-gpl** [comment]
At https://github.com/PyTables/PyTables/blob/f64704712c7b3b7940546e12d4d66958188ad220/tables/tests/test_tables.py#L5113 we try to create a table with a row of 640KB.

With numpy==1.14.2 (my version):
```
In [4]: np.rec.array([[np.arange(10)]*4])
Out[4]: 
rec.array([[(0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
            (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
            (0, 1, 2, 3, 4, 5, 6, 7, 8, 9),
            (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)]],
          dtype=[('f0', '<i8'), ('f1', '<i8'), ('f2', '<i8'), ('f3', '<i8'), ('f4', '<i8'), ('f5', '<i8'), ('f6', '<i8'), ('f7', '<i8'), ('f8', '<i8'), ('f9', '<i8')])
```

But with numpy==1.12.1:
```
In [4]: np.rec.array([[np.arange(10)]*4])
Out[4]: 
rec.array([[(0, 1, 2, 3), (0, 1, 2, 3), (0, 1, 2, 3), (0, 1, 2, 3)]],
          dtype=[('f0', '<i8'), ('f1', '<i8'), ('f2', '<i8'), ('f3', '<i8')])
In [5]: np.rec.array([[np.arange(40000)]*4])
Out[5]: 
rec.array([[(0, 1, 2, 3), (0, 1, 2, 3), (0, 1, 2, 3), (0, 1, 2, 3)]],
          dtype=[('f0', '<i8'), ('f1', '<i8'), ('f2', '<i8'), ('f3', '<i8')])
```

It seems a bug in older versions of numpy.

**Comment by tomkooij** [comment]
`3.4.3` was release to PyPI: So we need wheels.

I'm merging this to be able to create wheels.

**Comment by jsancho-gpl** [comment]
Thanks @tomkooij, my plan was to build the wheels during yesterday's evening and today, but I couldn't at the end, and the sources package had already been uploaded.

**Comment by tomkooij** [comment]
@jsancho-gpl Unfortunately, wheel building was not as easy as "update version". The wheelbuilder uses the external C-BLOSC because the pytables internal C-BLOSC enables AVX2 opcodes on travis builds. 
C-BLOSC will no longer build in de `manylinux` docker containers as it requires `CMake-2.8.12` is not supported in CentOS 5 (yes, v5).

The wheelbuilder (MacPython/pytables-wheels@abebcb20c852f3980b4b5a2f05c0b7ce97110880) now applies the same patch conda-forge uses to disable AVX2 in pytables setup.py

Wheels are being built and uploaded!

**Comment by tomkooij** [comment]
Wheels are on pypi!
conda packages are on conda-forge~!

**Pull request merged**
