### PR TITLE
Remove calls to numpy deprecated APIs

### PR DESCRIPTION
**Pull request by keszybz**
The tests pass, but I didn't do any benchmarking...

### CODE REVIEW

**Review by avalentino — APPROVED** [review]

**Comment by avalentino** [comment]
Thanks @keszybz, a very good job. A long awaited change actually ... :)
There is still some test failing.

On ubuntu it could be due to older version of some dependencies:

faling build
cython3 0.29.14
python3-numpy 1.17.4

successful build:
Cython-0.29.21
numpy-1.19.5

Not sure what happens in windows :/

**Comment by avalentino** [comment]
Merged in cf1dbbd0392f59316ac553491371dc774d3ac95d

**Comment by avalentino** [comment]
Builds on appveyor is still broken

**Comment by amotl** [comment]
@avalentino: Shall we also remove all AppVeyor and Travis CI stuff on behalf of #872?

**Comment by avalentino** [comment]
@amotl for appveyor I would say yes, in the current version of PR #872 we already cover all cases covered by appveyor in this moment.
Regarding travis, the only build left is on arm64 which I think is not supported natively by GHA.
Provably it is possible to use an emulator in GHA to cover also arm64 but it is still not implemented AFAIK.

**Comment by keszybz** [comment]
I added a few commits to fix a few more obvious warnings and hopefully the appveyor failure. It seems to fail only on windows, but I'm sure it's worth fixing since there are still windows users out there.

**Comment by amotl** [comment]
Hi Zbigniew,

> It seems to fail only on Windows, but I'm sure it's worth fixing since there are still windows users out there.

Definitively. Thanks a stack. Within #872, I just removed the AppVeyor artifacts and references through 6c524669. GitHub Actions is taking over.

Do you happen to have a Windows development environment? We are still looking for support on https://github.com/PyTables/PyTables/issues/823#issuecomment-770460668.

With kind regards,
Andreas.

**Comment by keszybz** [comment]
I missed one spot:
```
C:\projects\pytables\tables\tableextension.c(18028): error C2036: 'void *': unknown size
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
```

> I just removed the AppVeyor artifacts and references through 6c52466. GitHub Actions is taking over.

The compiler version is what's important. Based on the path above, it's version 14.0. According to https://en.wikipedia.org/wiki/Microsoft_Visual_Studio#History, that's Visual Studio 2015. It doesn't seem that old. I have no idea how to test other versions.

> May I ask if you happen to have a Windows development environment? We are still looking for support on [#823 (comment)](https://github.com/PyTables/PyTables/issues/823#issuecomment-770460668).

Nope :(

**Review by avalentino — APPROVED** [review]

**Comment by avalentino** [comment]
Thanks a lot @keszybz

**Pull request merged**
