### PR TITLE
Enable macos arm wheels

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by maxnoe** [comment]
@avalentino could it be that testing the wheels only works on the main repo and not via PRs from forks?

**Comment by avalentino** [comment]
Sorry @maxnoe , you are right.
Could I kindly ask you to add `pull-request:` in the `on` clause of the `workflows/wheels.yml` file?

```patch
# Publish when a (published) GitHub Release is created.
 on:
   push:
     branches:
       - master
       - 'releases/**'
       - 'ci/**'
     tags:
       - v*
+    pull_request:
```

**Comment by maxnoe** [comment]
We can also just continue in the other pr

**Comment by avalentino** [comment]
OK for me

**Pull request closed without merging**
