### PR TITLE
Release 3.6.0

### LINKED ISSUE #772: Python 2 pip selects PyTables 3.6.0, which is only available for python 3
Pytables 3.6.0 reports to pip that it is compatible with python 3, then issues an incompatibility message after the package is downloaded. This can be avoided by specifying the required python versions through `python_requires` in the `setup()` call in `setup.py`
```
$ python2 -m pip install tables
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting tables
  Using cached https://files.pythonhosted.org/packages/fb/b6/f7128895d328f64e52f61fbb39c03a458f8b583724705bddae392a1085a0/tables-3.6.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/wilsond1/venv/geopmpy2/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0GDTJd/tables/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0GDTJd/tables/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-0GDTJd/tables/pip-egg-info
         cwd: /tmp/pip-install-0GDTJd/tables/
    Complete output (1 lines):
    .. ERROR:: You need Python 3.4 or greater to install PyTables!
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

### PR DESCRIPTION
**Pull request by tomkooij**
TODO:
- [x] update `RELEASE-NOTES.txt` 
- [x] set `VERSION` (also in docs)
- [x] run `--heavy` test suite on Linux (or Mac)
- [x] run `--heavy` test suite on Windows.
- [x] merge into `master`
- [x] tag commit `v3.6.0`
- [x] update docs
- [x] create wheels (wheel builder at `MacPython/pytables-wheels`)
- [x] upload package and wheels to PyPI
- [x] update `conda-forge/pytables-feedstock` 
- [ ] post release actions
- [ ] fix #772 (by releasing 3.6.1)

Note to self: Make sure we upload package and wheels together to PyPI, to prevent problems with a "async release".

### CODE REVIEW

**Comment by tomkooij** [comment]
```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
PyTables version:    3.6.0
HDF5 version:        1.10.4
NumPy version:       1.17.2
Numexpr version:     2.7.0 (using VML/MKL 2019.0.4)
Zlib version:        1.2.11 (in Python interpreter)
BZIP2 version:       1.0.8 (13-Jul-2019)
Blosc version:       1.16.3 (2019-03-08)
Blosc compressors:   blosclz (1.1.0), lz4 (1.8.1), lz4hc (1.8.1), snappy (unknown), zlib (1.2.11), zstd (1.3.7)
Blosc filters:       shuffle, bitshuffle
Cython version:      0.29.13
Python version:      3.7.4 (default, Aug 13 2019, 20:35:49)
[GCC 7.3.0]
Platform:            Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Byte-ordering:       little
Detected cores:      12
Default encoding:    utf-8
Default FS encoding: utf-8
Default locale:      (en_US, UTF-8)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Performing the complete test suite!
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

----------------------------------------------------------------------
Ran 67296 tests in 10477.253s

OK (skipped=157)
```

**Comment by tomkooij** [comment]
I spent some time refactoring the wheelbuilder to build Windows wheels against a special HDF5 version (`pytables_hdf5.dll` instead of `hdf5.dll`) to prevent DLL Hell from/with our wheels.

This works when I do not build zlib support into HDF5, which makes sense for h5py but is stupid for PyTables. **But** building HDF5 with zlib enabled seems to take more than the allowed 1hour build time. Indeed it takes 1h20min for conda-forge/hdf5-feedstock to build on appveyor.

Anyway: I switched back to our old wheelbuilding. To try to do the release to PyPI (with wheels) today. I'll fix the Windows wheels after my holiday (I'll be back Oct 28th).

**Comment by FrancescAlted** [comment]
I feel your pain.

<rant>It is unfortunate that library maintainers have had to evolve towards becoming binary packagers, which is really hard and time consuming, most specially in Python (I have bad memories of the last wheels that I build for PyTables; they took much more time than I was comfortable to spend).  Binary packaging (at least wheels for complex Python extensions like PyTables) is so frustrating that I decided (almost sweared to myself) to avoid this kind of job in the future whenever possible </rant>.

We decidedly need to discuss if we, the maintainers, really want to take care of binary wheels, or let others to figure out how to produce them.

**Comment by tomkooij** [comment]
@FrancescAlted: I agree. Luckily, For our "usual" wheels, building was as easy as changing the build tag to `v3.6.0`. Then again, one can never be 100% sure the wheels actually work without breaking other stuff...

Hopefully I can fix the windows wheel building to fix "DLL Hell" (a little bit) sometime soon.

At least the wheels are built. I'll push the package to PyPI later this afternoon.

**Comment by tomkooij** [comment]
Uploaded to PyPI (+wheels).
Sent PR to conda-forge.

This is already merged into master, but I'll close/merge this once everything is ok/built.

**Comment by tomkooij** [comment]
All done!

**Comment by tomkooij** [comment]
I added stuff to TODO.

**Comment by tomkooij** [comment]
Closing for #775 
I will delete this release from PyPI once v3.6.1 is released to solve packaging issues.

**Pull request closed without merging**
