### PR TITLE
feat(group): autocomplete valid python-identifiers

### PR DESCRIPTION
**Pull request by ankostis**
Implement `__dir__()` on group nodes to include in the list of autocompletions also those children that are named as valid python identifiers.

### CODE REVIEW

**Comment by tomkooij** [comment]
I like it. Thanks. I'll be using this feature.

However, I'm having some issues:

This is the python 3.6 wheel build by appveyor for 762aecd in ipython 6.0 (python 3.6.1):

It shows an hdf5 file with `__dir__` and `__dir()__` called on a node (Group).

```python
In [14]: print(data)
2019_5_12.h5 (File) ''
Last modif.: 'Tue Apr 25 09:55:20 2017'
Object Tree:
/ (RootGroup) ''
/hisparc (Group) 'HiSPARC data'
/hisparc/cluster_groningen (Group) 'HiSPARC cluster Groningen data'
/hisparc/cluster_groningen/station_4004 (Group) 'HiSPARC station 4004 data'
/hisparc/cluster_groningen/station_4004/blobs (VLArray(28816,)) 'HiSPARC binary data'
/hisparc/cluster_groningen/station_4004/events (Table(14408,)) 'HiSPARC coincidences table'


In [15]: data.root.__dir__
Out[15]:
<bound method Group.__dir__ of / (RootGroup) ''
  children := ['hisparc' (Group)]>

In [16]: data.root.__dir__()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-16-b69cb7c07e83> in <module>()
----> 1 data.root.__dir__()

C:\Miniconda3\envs\test_dir\lib\site-packages\tables\group.py in __dir__(self)
    823         """Autocomplete only children named as valid python identifiers."""
    824         subnods = [c for c in self._v_children if _is_python_identifier(c)]
--> 825         return super(_Group, self).__dir__() + subnods
    826
    827     def __getattr__(self, name):

NameError: name '_Group' is not defined

In [17]:

```

A call to `__dir__()` should be added to a unittest.

Can you:
 - [ ] add `__dir__()` unittest (and fix)
 - [ ] add entry to `RELEASE_NOTES.txt`

Thanks for contributing.

**Comment by ankostis** [comment]
Both are now fixed (and discovered that PY-2 does not support `__dir__()`).

My apologies for not putting the effort to write a test-case;   I used GitHub's embedded editor to quickly copy from my working code.
Anyhow, thank you for the excellent response time.

**Comment by tomkooij** [comment]
Thanks!

I will merge this when CI is done.

I am going to use this feature!

**Comment by ankostis** [comment]
You may kill the appveyor jobs from all intermediate builds - they were git-rewrites proving nothing, just delaying the last one.

**Comment by ankostis** [comment]
Just a wishful thought:  
replicating [similar features of `h5py` base-classes](http://docs.h5py.org/en/latest/config.html#ipython) should not distract you from the [long awaited endeavor](https://hdfgroup.org/wp/2015/09/python-hdf5-a-vision/) of merging the two projects :-)

**Pull request merged**
