### PR TITLE
Set schunk when decompressing

### PR DESCRIPTION
**Pull request by froody**
Fixes https://github.com/PyTables/PyTables/issues/1109

### CODE REVIEW

**Review by avalentino — APPROVED** [review]
LGTM

**Comment by ivilata** [comment]
@avalentino: @FrancescAlted, @martaiborra and me had a look at this issue and Francesc planned to add some comments here that may be useful before merging the PR. Thanks! :slightly_smiling_face:

**Review by ivilata — COMMENTED** [review]
As I mentioned, Francesc had some comments on this, I just added him as a reviewer.

**Review by FrancescAlted — APPROVED** [review]
@froody .  The ultimate reason why you need this workaround is that you are not setting the typesize in the `filters_meta` field when appying the BYTEDELTA filter (see https://github.com/Blosc/c-blosc2/blob/2f8f6edca5a013cc5f9283be251e9cf1c7a00845/include/blosc2/filters-registry.h#L28).  Indeed, this was not your fault, as it was not documented before ;-)

Other than this, it probably does not hurt to apply your patch, and it actually helps in situations where filters would need to access metainfo stored in the `schunk`, so +1 on merging.  Bonus points if you can add a test exercising this.

**Comment by froody** [comment]
Ah, is there any benefit to setting the typesize on the filter meta? Can you save space in the compressed output by omitting the schunk header?

**Comment by froody** [comment]
So is this going to get merged or are you waiting on something?

**Comment by avalentino** [comment]
I was waiting for the test code requested by Francesc
Do you plan to add some unittests?

**Pull request merged**
